Repository openshift/metallb, pull requests merged in 2022-01, with the labels that each got.

#25 Bug 2038864: Upstream alignment
  e2etest/bgp_test.go
  website/content/configuration/weave.md
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#27 Bug 2040394: Controller: enqueue the failed configmap till services update
  controller/controller_test.go
  controller/main.go
Labels: bugzilla/severity-high, lgtm, approved, bugzilla/valid-bug

#26 Bug 2039507: fix updates to deployed addresspool and svc in any order
  controller/controller_test.go
  controller/main.go
  internal/k8s/k8s.go
  speaker/main.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent, cherry-pick-approved, backport-risk-assessed

#28 Bug 2041854: upstream sync
  .github/workflows/ci.yaml
  controller/service.go
  e2etest/bgp_test.go
  e2etest/bgptests/bgp.go
  e2etest/bgptests/infra_setup.go
  e2etest/bgptests/validate.go
  e2etest/e2etest_suite_test.go
  e2etest/l2tests/l2.go
  e2etest/pkg/config/parse.go
  e2etest/pkg/config/update.go
  e2etest/pkg/config/validate.go
  e2etest/pkg/frr/bgp.go
  e2etest/pkg/frr/config/config.go
  e2etest/pkg/frr/container/container.go
  e2etest/pkg/frr/validation.go
  e2etest/pkg/k8s/nodes.go
  e2etest/pkg/k8s/services.go
  e2etest/pkg/metallb/config.go
  e2etest/pkg/metallb/metallb.go
  e2etest/pkg/metrics/metrics.go
  e2etest/pkg/routes/routes.go
  e2etest/pkg/service/create.go
  e2etest/pkg/service/endpoints.go
  e2etest/pkg/wget/wget.go
  e2etest/utils.go
  internal/bgp/frr/config.go
  internal/bgp/frr/frr.go
  internal/bgp/frr/frr_test.go
  internal/bgp/frr/parse.go
  internal/bgp/frr/parse_test.go
  internal/bgp/frr/testdata/TestBFDWithSession.golden
  internal/bgp/frr/testdata/TestSingleAdvertisement.golden
  internal/bgp/frr/testdata/TestSingleAdvertisementChange.golden
  internal/bgp/frr/testdata/TestSingleAdvertisementInvalidPrefix.golden
  internal/bgp/frr/testdata/TestSingleAdvertisementNoRouterID.golden
  internal/bgp/frr/testdata/TestSingleAdvertisementStop.golden
  internal/bgp/frr/testdata/TestSingleEBGPSessionMultiHop.golden
  internal/bgp/frr/testdata/TestSingleEBGPSessionOneHop.golden
  internal/bgp/frr/testdata/TestSingleIBGPSession.golden
  internal/bgp/frr/testdata/TestTwoAdvertisements.golden
  internal/bgp/frr/testdata/TestTwoAdvertisementsTwoSessions.golden
  internal/bgp/frr/testdata/TestTwoSessions.golden
  internal/bgp/frr/testdata/TestTwoSessionsDuplicate.golden
  internal/bgp/frr/testdata/TestTwoSessionsDuplicateRouter.golden
  internal/config/validate.go
  internal/config/validate_test.go
  internal/ipfamily/ipfamily.go
  internal/k8s/k8s.go
  manifests/metallb-frr.yaml
  manifests/metallb.yaml
  manifests/prometheus-operator.yaml
  speaker/main.go
  tasks.py
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#30 Bug 2047238: FRR route-rules: add on-match next (#1201)
  e2etest/bgptests/bgp.go
  e2etest/pkg/frr/bgp.go
  internal/bgp/frr/config.go
  internal/bgp/frr/testdata/TestSingleAdvertisement.golden
  internal/bgp/frr/testdata/TestTwoAdvertisements.golden
  internal/bgp/frr/testdata/TestTwoAdvertisementsTwoSessions.golden
Labels: bugzilla/severity-high, lgtm, approved, bugzilla/valid-bug
