Repository openshift/metallb, pull requests merged in 2022-02, with the labels that each got.

#33 [release-4.9] Bug 2052549: L2: use externalips for speaker allocation
  speaker/bgp_controller.go
  speaker/layer2_controller.go
  speaker/layer2_controller_test.go
  speaker/main.go
Labels: qe-approved, staff-eng-approved, bugzilla/severity-high, lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed

#34 Bug 2056967: Speaker metrics: Bug fix: wrong label
  e2etest/l2tests/l2.go
  speaker/main.go
Labels: bugzilla/severity-high, lgtm, approved, bugzilla/valid-bug

#32 Move CI config files from dev-scripts repo
  openshift-ci/README.md
  openshift-ci/common.sh
  openshift-ci/deploy_metallb.sh
  openshift-ci/metallb-operator-deploy/controller_manager_patch.yaml
  openshift-ci/metallb-operator-deploy/kustomization.yaml
  openshift-ci/run_e2e.sh
Labels: lgtm, approved
