Repository openshift/metallb, pull requests merged in 2022-06, with the labels that each got.

#59 Bug 2089827: Refix backward compatibility patch
  openshift-ci/run_e2e.sh
Labels: bugzilla/severity-low, lgtm, approved, bugzilla/valid-bug

#60 Bug 2090755: Add validation for BGP and L2 advertisement
  internal/config/config.go
  internal/config/config_test.go
Labels: bugzilla/severity-low, lgtm, approved, bugzilla/valid-bug

#63 Bug 2097276: Openshift CI: deploy the operator via bundle
  openshift-ci/.gitignore
  openshift-ci/deploy_metallb.sh
  openshift-ci/metallb-operator-deploy/.gitignore
  openshift-ci/metallb-operator-deploy/build_and_push_index.sh
  openshift-ci/metallb-operator-deploy/controller_manager_patch.yaml
  openshift-ci/metallb-operator-deploy/install-resources.yaml
  openshift-ci/metallb-operator-deploy/kustomization.yaml
  openshift-ci/wait-for-csv.sh
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#65 Bug 2097047: Validate crd match expressions
  internal/config/config.go
  internal/config/config_test.go
Labels: bugzilla/severity-low, lgtm, approved, bugzilla/valid-bug

#66 Bug 2099875: Disable metrics endpoint in controller-runtime
  internal/k8s/k8s.go
Labels: lgtm, bugzilla/severity-unspecified, approved, bugzilla/valid-bug

#67 Bug 2100035: Fix MP BGP
  e2etest/bgptests/bgp.go
  e2etest/bgptests/bgp_multiprotocol.go
  e2etest/pkg/frr/config/config.go
  e2etest/pkg/frr/container/container.go
  e2etest/pkg/frr/validation.go
  e2etest/pkg/service/tweak.go
  internal/bgp/frr/config.go
  internal/bgp/frr/frr.go
  internal/bgp/frr/parse.go
  internal/bgp/frr/testdata/TestBFDWithSession.golden
  internal/bgp/frr/testdata/TestSingleAdvertisement.golden
  internal/bgp/frr/testdata/TestSingleAdvertisementChange.golden
  internal/bgp/frr/testdata/TestSingleAdvertisementNoRouterID.golden
  internal/bgp/frr/testdata/TestSingleAdvertisementNonExistingPeer.golden
  internal/bgp/frr/testdata/TestSingleAdvertisementStop.golden
  internal/bgp/frr/testdata/TestSingleAdvertisementWithPeerSelector.golden
  internal/bgp/frr/testdata/TestSingleEBGPSessionMultiHop.golden
  internal/bgp/frr/testdata/TestSingleEBGPSessionOneHop.golden
  internal/bgp/frr/testdata/TestSingleIBGPSession.golden
  internal/bgp/frr/testdata/TestSingleIPv6EBGPSessionOneHop.golden
  internal/bgp/frr/testdata/TestSingleIPv6IBGPSession.golden
  internal/bgp/frr/testdata/TestTwoAdvertisements.golden
  internal/bgp/frr/testdata/TestTwoAdvertisementsTwoSessions.golden
  internal/bgp/frr/testdata/TestTwoAdvertisementsTwoSessionsOneWithPeerSelector.golden
  internal/bgp/frr/testdata/TestTwoIPv6Sessions.golden
  internal/bgp/frr/testdata/TestTwoSessions.golden
  internal/bgp/frr/testdata/TestTwoSessionsDuplicate.golden
  internal/bgp/frr/testdata/TestTwoSessionsDuplicateRouter.golden
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
