Repository openshift/metallb, pull requests merged in 2023-06, with the labels that each got.

#124 OCPBUGS-14277: 4.11 backport: read memberlist secret from file instead of env var
  charts/metallb/README.md
  charts/metallb/policy/speaker.rego
  charts/metallb/templates/speaker.yaml
  charts/metallb/values.schema.json
  charts/metallb/values.yaml
  config/controllers/speaker.yaml
  config/manifests/metallb-frr.yaml
  config/manifests/metallb-native.yaml
  internal/k8s/k8s.go
  speaker/main.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#127 OCPBUGS-14410: Backport the extra frr configuration to 4.13
  e2etest/bgptests/bgp.go
  e2etest/bgptests/validate.go
  e2etest/pkg/frr/bgp.go
  e2etest/pkg/frr/config/config.go
  e2etest/pkg/k8s/configmap.go
  internal/bgp/bgp.go
  internal/bgp/frr/config.go
  internal/bgp/frr/frr.go
  internal/bgp/frr/frr_test.go
  internal/bgp/frr/templates/frr.tmpl
  internal/bgp/frr/testdata/TestSingleSessionExtras.golden
  internal/bgp/native/native.go
  internal/config/config.go
  internal/k8s/controllers/config_controller.go
  internal/k8s/controllers/dump.go
  internal/k8s/k8s.go
  openshift-ci/run_e2e.sh
  speaker/bgp_controller.go
  speaker/bgp_controller_test.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#129 OCPBUGS-14503: [4.10] read memberlist secret from file instead of env var
  charts/metallb/README.md
  charts/metallb/policy/speaker.rego
  charts/metallb/templates/speaker.yaml
  charts/metallb/values.schema.json
  charts/metallb/values.yaml
  internal/k8s/k8s.go
  manifests/metallb-frr.yaml
  manifests/metallb.yaml
  speaker/main.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#132 OCPBUGS-15415: don't reload when not necessary
  internal/bgp/frr/frr.go
  internal/bgp/frr/frr_test.go
  internal/k8s/controllers/config_controller.go
  internal/k8s/controllers/config_conversion.go
  internal/k8s/controllers/config_conversion_test.go
  internal/k8s/controllers/pool_controller.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference
