Repository openshift/metallb, pull requests merged in 2024-10, with the labels that each got.

#197 [release-4.13] OCPBUGS-41931: Make localPref uniform among updates
  api/v1beta1/bgpadvertisement_webhook.go
  api/v1beta1/bgpadvertisement_webhook_test.go
  api/v1beta1/mock_validator_test.go
  charts/metallb/templates/rbac.yaml
  config/manifests/metallb-frr-prometheus.yaml
  config/manifests/metallb-frr.yaml
  config/manifests/metallb-native-prometheus.yaml
  config/manifests/metallb-native.yaml
  config/rbac/role.yaml
  go.mod
  internal/config/config.go
  internal/config/config_test.go
  internal/config/validator.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#200 FRR-K8S via CNO fixes
  openshift-ci/deploy_metallb.sh
  openshift-ci/run_e2e.sh
Labels: lgtm, approved

#202 OCPBUGS-25783: D/S only: fix the frr path used by tests
  e2etest/pkg/frr/container/container.go
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#203 Openshift CI: fix oc exec
  openshift-ci/deploy_metallb.sh
Labels: lgtm, approved

#198 Openshift CI: run frr-k8s e2e tests
  openshift-ci/deploy_metallb.sh
  openshift-ci/enable_frrk8s_on_cno.sh
  openshift-ci/run_e2e.sh
  openshift-ci/run_frrk8s_e2e.sh
  openshift-ci/run_metallb_e2e.sh
Labels: lgtm, approved
